### 管理员登录
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "number": "admin",
  "password": "admin"
}

### 导师登录
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "number": "12345",
  "password": "12345"
}

### 学生登录
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "number": "2022212916",
  "password": "2022212916"
}