### 获取该过程的评分
GET http://localhost:8080/api/student/processScore/1385934577505820672
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxMzgyODI2MjgxOTI5OTI3MjkzIiwicm9sZSI6InVXcTIiLCJkZXBhcnRtZW50SWQiOiIxMzg1ODY4OTE3MTMyMTI0MTYwIiwiZ3JvdXBOdW1iZXIiOjIsImlhdCI6MTc1MDc2MDA4NiwiZXhwIjoxNzUwODQ2NDg2fQ.ZbwiaXy9hxgMqtWgknQtdKKueFzjS6PZO5kW3i6n_nE
