### 创建导师和学生都可见的子项
POST http://localhost:8080/api/teacher/process
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXBhcnRtZW50SWQiOiIxMzg1ODY4OTE3MTMyMTI0MTYwIiwiZ3JvdXBOdW1iZXIiOjIsInVpZCI6IjEzODU4MjY3ODk5NjY5MjcyOTYiLCJyb2xlIjoiYlUzZSIsImlhdCI6MTc1MDU2MjQ4NCwiZXhwIjoxNzUwNjQ4ODg0fQ.bpPliRHQz94QOo8RTS3ylHhIx3b_0x8aeFKBiR2xVWM
Content-Type: application/json

{
  "name": "开题答辩",
  "items":  "[{\"number\":\"1\",\"name\":\"选题依据\",\"point\":50,\"description\":\"毕业设计的选题依据\"},{\"number\":\"2\",\"name\":\"设计方案\",\"point\":25,\"description\":\"毕业设计的设计方案\"},{\"number\":\"3\",\"name\":\"答辩\",\"point\":25,\"description\":\"毕业设计的答辩\"}]",
  "point": 30,
  "auth": "TEA01",
  "student_attach": "[{\"number\":\"1\",\"name\":\"开题答辩报告\",\"ext\":\"pdf\",\"description\":\"需清晰可见有效期\"}]"
}

### 创建只有导师可见的子项
POST http://localhost:8080/api/teacher/process
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxMzg1ODI2Nzg5OTY2OTI3Mjk2Iiwicm9sZSI6ImJVM2UiLCJkZXBhcnRtZW50SWQiOiIxMzg1ODY4OTE3MTMyMTI0MTYwIiwiZ3JvdXBOdW1iZXIiOjIsImlhdCI6MTc1MDU3NjgwNSwiZXhwIjoxNzUwNjYzMjA1fQ.3QUjnPZSYgqatGiAOb4QMUFPV_mR19fKtFNyks9R5Qc
Content-Type: application/json

{
  "name": "答辩中期",
  "items":  "[{\"number\":\"1\",\"name\":\"选题论述\",\"point\":50,\"description\":\"毕业设计的选题论述\"},{\"number\":\"2\",\"name\":\"设计展开\",\"point\":25,\"description\":\"毕业设计的设计展开\"},{\"number\":\"3\",\"name\":\"答辩\",\"point\":25,\"description\":\"毕业设计的答辩\"}]",
  "point": 20,
  "auth": "Pbu45",
  "student_attach": "[{\"number\":\"1\",\"name\":\"答辩中期报告\",\"ext\":\"pdf\",\"description\":\"需清晰可见有效期\"}]"
}

### 导师删除过程(路径参数)
DELETE http://localhost:8080/api/teacher/process/1386187998511128576
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXBhcnRtZW50SWQiOiIxMzg1ODY4OTE3MTMyMTI0MTYwIiwiZ3JvdXBOdW1iZXIiOjIsInVpZCI6IjEzODU4MjY3ODk5NjY5MjcyOTYiLCJyb2xlIjoiYlUzZSIsImlhdCI6MTc1MDU2MjQ4NCwiZXhwIjoxNzUwNjQ4ODg0fQ.bpPliRHQz94QOo8RTS3ylHhIx3b_0x8aeFKBiR2xVWM

### 导师修改子项
POST http://localhost:8080/api/teacher/process
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXBhcnRtZW50SWQiOiIxMzg1ODY4OTE3MTMyMTI0MTYwIiwiZ3JvdXBOdW1iZXIiOjIsInVpZCI6IjEzODU4MjY3ODk5NjY5MjcyOTYiLCJyb2xlIjoiYlUzZSIsImlhdCI6MTc1MDU2MjQ4NCwiZXhwIjoxNzUwNjQ4ODg0fQ.bpPliRHQz94QOo8RTS3ylHhIx3b_0x8aeFKBiR2xVWM
Content-Type: application/json

{
  "id": "1386194177400397824",
  "name": "修改后的过程",
  "items":  "[{\"number\":\"1\",\"name\":\"选题论述\",\"point\":50,\"description\":\"毕业设计的选题论述\"},{\"number\":\"2\",\"name\":\"设计展开\",\"point\":25,\"description\":\"毕业设计的设计展开\"},{\"number\":\"3\",\"name\":\"答辩\",\"point\":25,\"description\":\"毕业设计的答辩\"}]",
  "point": 20,
  "auth": "Pbu45",
  "student_attach": "[{\"number\":\"1\",\"name\":\"答辩中期报告\",\"ext\":\"pdf\",\"description\":\"需清晰可见有效期\"}]"
}

### 获取该导师指导的所有学生
GET http://localhost:8080/api/teacher/students/teach
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxMzg1ODI2Nzg5OTY2OTI3Mjk2Iiwicm9sZSI6ImJVM2UiLCJkZXBhcnRtZW50SWQiOiIxMzg1ODY4OTE3MTMyMTI0MTYwIiwiZ3JvdXBOdW1iZXIiOjIsImlhdCI6MTc1MDU3NzcyMCwiZXhwIjoxNzUwNjY0MTIwfQ.aVO-r5NaH84Q067GSLzw_33wS7Q3GRkXtvbNuKEXr00

### 获取某组的学生
GET http://localhost:8080/api/teacher/students/group
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxMzg1ODI2Nzg5OTY2OTI3Mjk2Iiwicm9sZSI6ImJVM2UiLCJkZXBhcnRtZW50SWQiOiIxMzg1ODY4OTE3MTMyMTI0MTYwIiwiZ3JvdXBOdW1iZXIiOjIsImlhdCI6MTc1MDU3NzcyMCwiZXhwIjoxNzUwNjY0MTIwfQ.aVO-r5NaH84Q067GSLzw_33wS7Q3GRkXtvbNuKEXr00

### 导师评分(无id创建，有id更新)
POST http://localhost:8080/api/teacher/processScore/1382826281929927293/1385934577505820672
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxMzg1ODI2Nzg5OTY2OTI3Mjk2Iiwicm9sZSI6ImJVM2UiLCJkZXBhcnRtZW50SWQiOiIxMzg1ODY4OTE3MTMyMTI0MTYwIiwiZ3JvdXBOdW1iZXIiOjIsImlhdCI6MTc1MDU4Mjc3MSwiZXhwIjoxNzUwNjY5MTcxfQ.EC8JiOx0Z2TuY2tiV3WZpBzBZtn5ZspthDFub8BwEnY
Content-Type: application/json

{
  "id": "1386269736033738752",
  "detail":  "{\"teacherName\":\"王波老师\",\"score\":91.2,\"detail\":[{\"number\":\"QUIZ001\",\"score\":95},{\"number\":\"ASSIGN002\",\"score\":88},{\"number\":\"FINAL_EXAM\",\"score\":90}]}"
}

### 获取该导师给某过程的评分
GET http://localhost:8080/api/teacher/processScore/1385934577505820672
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxMzg1ODI2Nzg5OTY2OTI3Mjk2Iiwicm9sZSI6ImJVM2UiLCJkZXBhcnRtZW50SWQiOiIxMzg1ODY4OTE3MTMyMTI0MTYwIiwiZ3JvdXBOdW1iZXIiOjIsImlhdCI6MTc1MDU5MzUxNCwiZXhwIjoxNzUwNjc5OTE0fQ.olqZQyFXxIP73wZNlfEFoV4tae6csQyIxY7djPdPvsc
